name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: self-hosted  # Use a self-hosted runner

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker registry
      - name: Log in to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build and push frontend image to Docker Hub
      - name: Build and push frontend
        run: |
          docker build -t arystan321/frontend:latest ./frontend
          docker push arystan321/frontend:latest

      # Step 4: Build and push backend image to Docker Hub
      - name: Build and push backend
        run: |
          docker build -t arystan321/backend:latest ./backend
          docker push arystan321/backend:latest

      # Step 5: Deploy stack to Docker Swarm
      - name: Deploy stack to Docker Swarm
        run: |
          docker stack deploy -c docker-compose.yml arys
