name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push frontend
        run: |
          docker build -t arystan321/frontend:latest ./frontend
          docker push arystan321/frontend:latest

      - name: Build and push backend
        run: |
          docker build -t arystan321/backend:latest ./backend
          docker push arystan321/backend:latest

      - name: Deploy stack to Docker Swarm
        run: |
          docker stack deploy -c docker-compose.yml arys
