version: '3.8'

services:
  frontend:
    image: yourdockerhub/frontend:latest
    deploy:
      placement:
        constraints:
          - node.hostname == workerone
    ports:
      - "3000:3000"

  backend:
    image: yourdockerhub/backend:latest
    deploy:
      placement:
        constraints:
          - node.hostname == workertwo
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    deploy:
      placement:
        constraints:
          - node.hostname == masternode
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
