name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the pipeline on every commit to the main branch

jobs:
  build:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t myapp:${{ github.sha }} .
    
    - name: Push Docker image to registry
      run: |
        docker tag myapp:${{ github.sha }} yourdockerhubusername/myapp:${{ github.sha }}
        docker push yourdockerhubusername/myapp:${{ github.sha }}

  deploy:
    runs-on: self-hosted  # Ensure deploy runs on a server in your Docker Swarm cluster
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: SSH into Master Node to Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 24.199.103.13  # Master node IP
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Pull the latest Docker image
          docker pull yourdockerhubusername/myapp:${{ github.sha }}
          
          # Deploy to Docker Swarm
          docker stack deploy -c docker-compose.yml myapp
          
          # Update service if necessary
          docker service update --image yourdockerhubusername/myapp:${{ github.sha }} myapp_backend
          docker service update --image yourdockerhubusername/myapp:${{ github.sha }} myapp_frontend

